CREATE DATABASE DB_BANCO;
USE DB_BANCO;

CREATE TABLE CLIENTE
(
COD_CLIENTE INT NOT NULL,
NOM_CLIENTE VARCHAR(100) NOT NULL,
NUM_CPF_CNPJ VARCHAR(100) NOT NULL,
NUM_CELULAR VARCHAR(100) NOT NULL,
DES_ENDERECO VARCHAR(100) NOT NULL,
COD_CATEGORIA_CLIENTE INT NOT NULL
);

CREATE TABLE CATEGORIA_CLIENTE
(
COD_CATEGORIA_CLIENTE INT NOT NULL,
NOM_CATEGORIA_CLIENTE VARCHAR(100)
);

CREATE TABLE AGENCIA
(
COD_AGENCIA INT NOT NULL,
NOM_AGENCIA VARCHAR(100) NOT NULL
);

CREATE TABLE TIPO_CONTA
(
COD_TIPO_CONTA INT NOT NULL,
DES_TIPO_CONTA VARCHAR(100)
);

CREATE TABLE CONTA
(
NUM_CONTA INT NOT NULL,
VAL_SALDO FLOAT (8,2),
COD_TIPO_CONTA INT NOT NULL,
COD_CLIENTE INT NOT NULL,
COD_AGENCIA INT NOT NULL
);

CREATE TABLE HISTORICO_MOVIMENTACAO
(
COD_HISTORICO_MOVIMENTACAO INT NOT NULL,
NUM_CONTA INT NOT NULL, 
COD_TIPO_MOVIMENTACAO INT NOT NULL,
VAL_MOVIMENTADO FLOAT (8,2),
DTA_MOVIMENTACAO DATE
);

CREATE TABLE TIPO_MOVIMENTACAO
(
COD_TIPO_MOVIMENTACAO INT NOT NULL,
DES_TIPO_MOVIMENTACAO VARCHAR(200) NOT NULL,
VAL_TAXA FLOAT (8,2),
IND_DEBITO_CREDITO CHAR(1)
);

ALTER TABLE CLIENTE ADD PRIMARY KEY (COD_CLIENTE);
ALTER TABLE CATEGORIA_CLIENTE ADD PRIMARY KEY (COD_CATEGORIA_CLIENTE);
ALTER TABLE AGENCIA ADD PRIMARY KEY (COD_AGENCIA);
ALTER TABLE TIPO_CONTA ADD PRIMARY KEY (COD_TIPO_CONTA);
ALTER TABLE CONTA ADD PRIMARY KEY (NUM_CONTA);
ALTER TABLE TIPO_MOVIMENTACAO ADD PRIMARY KEY (COD_TIPO_MOVIMENTACAO);
ALTER TABLE HISTORICO_MOVIMENTACAO ADD PRIMARY KEY (COD_HISTORICO_MOVIMENTACAO);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_COD_CLIENTE_CATEGORIACLIENTE
FOREIGN KEY (COD_CATEGORIA_CLIENTE)
REFERENCES CATEGORIA_CLIENTE (COD_CATEGORIA_CLIENTE);

ALTER TABLE CONTA ADD CONSTRAINT FK_COD_CONTA_TIPOCONTA
FOREIGN KEY (COD_TIPO_CONTA)
REFERENCES TIPO_CONTA (COD_TIPO_CONTA);

ALTER TABLE CONTA ADD CONSTRAINT FK_COD_CONTA_CLIENTE
FOREIGN KEY (COD_CLIENTE)
REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE CONTA ADD CONSTRAINT FK_COD_CONTA_AGENCIA
FOREIGN KEY (COD_AGENCIA)
REFERENCES AGENCIA (COD_AGENCIA);

ALTER TABLE HISTORICO_MOVIMENTACAO ADD CONSTRAINT FK_COD_HISTORICO_CONTA
FOREIGN KEY (NUM_CONTA)
REFERENCES CONTA (NUM_CONTA);

ALTER TABLE HISTORICO_MOVIMENTACAO ADD CONSTRAINT FK_COD_HISTORICO_TIPO
FOREIGN KEY (COD_TIPO_MOVIMENTACAO)
REFERENCES TIPO_MOVIMENTACAO (COD_TIPO_MOVIMENTACAO);

INSERT INTO CATEGORIA_CLIENTE (COD_CATEGORIA_CLIENTE, NOM_CATEGORIA_CLIENTE)
VALUES (1, 'Pessoal');
INSERT INTO CATEGORIA_CLIENTE (COD_CATEGORIA_CLIENTE, NOM_CATEGORIA_CLIENTE)
VALUES (2, 'Empresa');

INSERT INTO AGENCIA (COD_AGENCIA, NOM_AGENCIA)
VALUES (1, 'Pampulha');

INSERT INTO TIPO_CONTA (COD_TIPO_CONTA, DES_TIPO_CONTA)
VALUES (1, 'Corrente');
INSERT INTO TIPO_CONTA (COD_TIPO_CONTA, DES_TIPO_CONTA)
VALUES (2, 'Poupança');

INSERT INTO CLIENTE (COD_CLIENTE, NOM_CLIENTE, NUM_CPF_CNPJ, NUM_CELULAR, DES_ENDERECO, COD_CATEGORIA_CLIENTE)
VALUES (1, 'Julia Souza', '1271271277', '999129977', 'Rua Joaquim Pereira 480', 1);

INSERT INTO CONTA (NUM_CONTA, VAL_SALDO, COD_TIPO_CONTA, COD_CLIENTE, COD_AGENCIA)
VALUES (1, 1000000, 1, 1, 1);

INSERT INTO TIPO_MOVIMENTACAO (COD_TIPO_MOVIMENTACAO, DES_TIPO_MOVIMENTACAO, VAL_TAXA, IND_DEBITO_CREDITO)
VALUES (1, 'PIX', 0, 'C');

INSERT INTO HISTORICO_MOVIMENTACAO (COD_HISTORICO_MOVIMENTACAO, NUM_CONTA, COD_TIPO_MOVIMENTACAO, VAL_MOVIMENTADO, DTA_MOVIMENTACAO)
VALUES (1, 1, 1, 100000, '2023-03-24');

